/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dbca;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ETPL_CH_01
 */
public class lca extends javax.swing.JFrame {
static ArrayList al=nextwindow.al;
static ArrayList al1=nextwindow.al1;
static int finalcutvalue=nextwindow.finalcutvalue;
Statement st,st1,st2;
     Connection con;
     static int vr1=split.vr1;
    /**
     * Creates new form lca
     */
    public lca() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbca", "root", "");
            st = con.createStatement();
            st1 = con.createStatement();
            st2=con.createStatement();
//        st.executeUpdate("truncate table batch3");
        st.executeUpdate("truncate table app");
        st.executeUpdate("truncate table app1");
        
        } catch (ClassNotFoundException | SQLException e) {
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButton1.setText("LCA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("view");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Frequent Subsets");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try
       {
           int j=1,k=1;
          for(int i=3;i<=(vr1/10);)
          {
           jTextArea1.append(" Batch"+i+" \n ------------------- \n");
           ResultSet rs=st.executeQuery("select distinct(count) from batch"+i+" order by count desc");
           while(rs.next())
           {
               String acc=rs.getString(1);
               ResultSet rs1=st1.executeQuery("select count(count) from batch"+i+" where count='"+acc +"'");
               
               while(rs1.next())
               {
                   int h=j++;;
                   String value=rs1.getString(1);
//                   System.out.println(acc+"->" +value +"->"+(j++));
                   jTextArea1.append(acc+"->" + value + "->" +h+"->" +"batch"+i +"\n");
                   st2.executeUpdate("insert into app values('" +acc + "','" + value + "','"+h + "','" +"batch"+i+"')");
               }
           }
           i=i+2;
          
//           jTextArea1.append(" Batch4 \n0 ------------------- \n");
//           ResultSet rs3=st.executeQuery("select distinct(count) from batch3 order by count desc");
//           while(rs3.next())
//           {
//               String acc=rs3.getString(1);
//               ResultSet rs1=st1.executeQuery("select count(count) from batch3 where count='"+acc +"'");
//               while(rs1.next())
//               {
//                   String value=rs1.getString(1);
//                   int f=k++;
//                   System.out.println(acc+"->" +value +"->"+f);
//                   jTextArea1.append(acc+"->" + value + "->" +f +"\n");
//                   st2.executeUpdate("insert into app1 values('" +acc + "','" + value + "','"+f + "')");
//               }
//           }
           
           JOptionPane.showMessageDialog(null,"LCA computed");
       }
       }
       catch(SQLException | HeadlessException e)
       {
           System.out.println(e.getMessage());
       }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try
      {
           int i=0,j=0;
           for(int k=3;k<(vr1/10);)
           {
          ResultSet rs=st.executeQuery("select priority from app where batch='" +"batch"+k +"'\tORDER BY priority asc");
          while(rs.next())
          {
              ResultSet rs1=st1.executeQuery("select count1 from app where priority='"+rs.getString(1) +"' AND batch='batch"+k+"'" );
              while(rs1.next())
              {
                 
                  if(i<finalcutvalue)
                  {
                      st2.executeUpdate("delete from batch"+k+" where count='" +rs1.getString(1)+"'"  );
                     
                  }
                   i++;
              }
          }
          k+=2;
           }
//           ResultSet rs2=st.executeQuery("select priority from app1 ORDER BY priority asc");
//          while(rs2.next())
//          {
//              ResultSet rs1=st1.executeQuery("select count from app1 where priority='"+rs2.getString(1) +"'" );
//              while(rs1.next())
//              {
//                 
//                  if(j<finalcutvalue)
//                  {
//                      st2.executeUpdate("delete from batch4 where count='" +rs1.getString(1)+"'"  );
//                      j++;
//                  }
//                  
//              }
//          }
          JOptionPane.showMessageDialog(null," deleted");
      }
      catch(SQLException | HeadlessException e)
      {
          System.out.println(e.getMessage());
      }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   try
   {
       for(int i=3;i<(vr1/10);)
   {
       jTextArea1.append("remaining data\n batch"+i +"\n--------------------\n");
       ResultSet rs=st.executeQuery("select * from batch"+i);
       while(rs.next())
       {
           String va=rs.getString(2);
           jTextArea1.append(va + "\n");
           st1.executeUpdate("insert into batchfinal values('" +va +"')");
       }
       i+=2;
//       jTextArea1.append("batch4\n-------------------------\n");
//       ResultSet rs1=st.executeQuery("select * from batch4");
//       while(rs1.next())
//       {
//           jTextArea1.append(rs1.getString(1) + "\n");
//       }
   } 
   }
   catch(Exception e){
       System.out.println(e.getMessage());
   }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lca().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
