/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dbca;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ETPL_CH_01
 */
public class split extends javax.swing.JFrame {
  Statement st,st1;
     Connection con;
     static  int vr1;
    /**
     * Creates new form split
     */
    public split() {
        initComponents();
          try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbca", "root", "");
            st = con.createStatement();
            st1 = con.createStatement();
             st.executeUpdate("drop table batch3");
            st.executeUpdate("drop table batch4");
            st.executeUpdate("drop table batch5");
             st.executeUpdate("drop table batch6");
              st.executeUpdate("drop table batch7");
               st.executeUpdate("drop table batch8");
                st.executeUpdate("drop table batch9");
                st.executeUpdate("drop table batch10");
                
//            st.executeUpdate("truncate table ");
        } catch (ClassNotFoundException | SQLException e) {
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel2.setText("Batch Formation");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jButton1.setText("Batch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("view");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Window");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addComponent(jButton3)
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String vr = null;
        try
    {
        ResultSet rs=st.executeQuery("Select count(*) from home");
        while(rs.next())
        {
        vr=rs.getString(1);
        System.out.println(vr);
    }
       vr1=Integer.parseInt(vr);
        for(int i=1;i<=(vr1/10);i++)
        {
            jComboBox1.addItem("Batch"+(i));
            if(i>2)
            {
            st.executeUpdate("create table batch"+i +" ( id varchar(50),string varchar(50) ,count varchar(50)) ");
            }
        }
        JOptionPane.showMessageDialog(null," Batching process completed");
    }
        
    catch(SQLException | NumberFormatException | HeadlessException e)
    {
        System.out.println(e.getMessage());
    }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        try
       {
           if(jComboBox1.getSelectedItem().equals("Batch1"))
           {
                    jTextArea1.append("Batch 1" + "\n" + "_______________" + "\n");
               ResultSet rs=st.executeQuery("Select *  from home where tid between 1 and 10");
               while(rs.next())
               {
                   String s=rs.getString(1);
                   String s1=rs.getString(2);
              
                   jTextArea1.append(s + "-------" +s1 + "\n");
//                   st1.executeUpdate("insert into batch1 values('" +s +"','" +s1 +"','" +" "+"')");
               }
           }
           else if(jComboBox1.getSelectedItem().equals("Batch2"))
           {
                   jTextArea1.append("Batch 2" + "\n" + "_______________" + "\n" );
               ResultSet rs=st.executeQuery("Select *  from home where tid between 11 and 20");
               while(rs.next())
               {
                   String s=rs.getString(1);
                   String s1=rs.getString(2);
               
                   jTextArea1.append(s + "," +s1 + "\n");
//                   st1.executeUpdate("insert into batch2 values('" +s +"','" +s1 +"')");
               }
           }
           else if(jComboBox1.getSelectedItem().equals("Batch3"))
           {
                  jTextArea1.append("Batch 3" + "\n" + "_______________" + "\n");
               ResultSet rs=st.executeQuery("Select *  from home where tid between 21 and 30");
               while(rs.next())
               {
                   String s=rs.getString(1);
                   String s1=rs.getString(2);
                
                   jTextArea1.append(s + "," +s1 + "\n");
//                    st1.executeUpdate("insert into batch3 values('" +s +"','" +s1 +"')");
               }
           }
           else  if(jComboBox1.getSelectedItem().equals("Batch4"))
           {
                   jTextArea1.append("Batch 4" + "\n" + "_______________" + "\n");
               ResultSet rs=st.executeQuery("Select *  from home where tid between 31 and 40");
               while(rs.next())
               {
                   String s=rs.getString(1);
                   String s1=rs.getString(2);
               
                   jTextArea1.append(s + "," +s1 + "\n");
//                    st1.executeUpdate("insert into batch4 values('" +s +"','" +s1 +"')");
               }
           }
           else  if(jComboBox1.getSelectedItem().equals("Batch5"))
           {
                    jTextArea1.append("Batch 5" + "\n" + "_______________" + "\n");
               ResultSet rs=st.executeQuery("Select *  from home where tid between 41 and 50");
               while(rs.next())
               {
                   String s=rs.getString(1);
                   String s1=rs.getString(2);
              
                   jTextArea1.append(s + "," +s1 + "\n");
//                    st1.executeUpdate("insert into batch5 values('" +s +"','" +s1 +"')");
               }
           }
           else  if(jComboBox1.getSelectedItem().equals("Batch6"))
           {
                    jTextArea1.append("Batch 6" + "\n" + "_______________" + "\n");
               ResultSet rs=st.executeQuery("Select *  from home where tid between 51 and 60");
               while(rs.next())
               {
                   String s=rs.getString(1);
                   String s1=rs.getString(2);
              
                   jTextArea1.append(s + "," +s1 + "\n");
//                    st1.executeUpdate("insert into batch6 values('" +s +"','" +s1 +"')");
               }
           }
          else if(jComboBox1.getSelectedItem().equals("Batch7"))
           {
                jTextArea1.append("Batch 7" + "\n" + "_______________" + "\n");
               ResultSet rs=st.executeQuery("Select *  from home where tid between 61 and 70");
               while(rs.next())
               {
                   String s=rs.getString(1);
                   String s1=rs.getString(2);
                  
                   jTextArea1.append(s + "," +s1 + "\n");
//                    st1.executeUpdate("insert into batch7 values('" +s +"','" +s1 +"')");
               }
           }
          else  if(jComboBox1.getSelectedItem().equals("Batch8"))
           {
                 jTextArea1.append("Batch 8" + "\n" + "_______________" + "\n");
               ResultSet rs=st.executeQuery("Select *  from home where tid between 71 and 80");
               while(rs.next())
               {
                   String s=rs.getString(1);
                   String s1=rs.getString(2);
                 
                   jTextArea1.append(s + "," +s1 + "\n");
//                    st1.executeUpdate("insert into batch8 values('" +s +"','" +s1 +"')");
               }
           }
          else   if(jComboBox1.getSelectedItem().equals("Batch9"))
           {
                jTextArea1.append("Batch 9" + "\n" + "_______________" + "\n");
               ResultSet rs=st.executeQuery("Select *  from home where tid between 81 and 90");
               while(rs.next())
               {
                   String s=rs.getString(1);
                   String s1=rs.getString(2);
                  
                   jTextArea1.append(s + "," +s1 + "\n");
//                    st1.executeUpdate("insert into batch9 values('" +s +"','" +s1 +"')");
               }
           }
          else  if(jComboBox1.getSelectedItem().equals("Batch10"))
           {
                 jTextArea1.append("Batch 10" + "\n" + "----------------" + "\n");
               ResultSet rs=st.executeQuery("Select *  from home where tid between 91 and 100");
               while(rs.next())
               {
                   String s=rs.getString(1);
                   String s1=rs.getString(2);
                 
                   jTextArea1.append(s + "," +s1 + "\n");
//                    st1.executeUpdate("insert into batch10 values('" +s +"','" +s1 +"')");
               }
           }
           else
          {
              JOptionPane.showMessageDialog(null," Select batch to view");
          }
       }

        catch(SQLException | HeadlessException e)
       {
           System.out.println(e.getMessage());
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new window().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(split.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(split.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(split.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(split.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new split().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
