/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dbca;

import java.util.ArrayList;

/**
 *
 * @author seabirds
 */
public class SubsetFrame extends javax.swing.JFrame {

    /**
     * Creates new form BaseInfoFrame
     */
     MainFrame mf;
    ArrayList it1=new ArrayList();
    ArrayList it2=new ArrayList();
    ArrayList it3=new ArrayList();
    
    ArrayList itc1=new ArrayList();
    ArrayList itc2=new ArrayList();
    ArrayList itc3=new ArrayList();
    
    public SubsetFrame(MainFrame me) 
    {
        mf=me;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel1.setText("Item Subset Count");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Cambria Math", 0, 17)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Cambria Math", 0, 17)); // NOI18N
        jButton1.setText("Find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 17)); // NOI18N
        jLabel2.setText("Skip-and- Complete");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            /*System.out.println("----> "+mf.item1);
            ArrayList at1=new ArrayList();
            for(int i=0;i<mf.item1.size();i++)
            {
                String g1=mf.item1.get(i).toString();
                for(int j=i+1;j<mf.item1.size();j++)
                {
                    String g2=mf.item1.get(j).toString();
                    //for(int k=j+1;k<mf.item1.size();k++)
                    for(int k=j+1;k<mf.item1.size();k+=2)
                    {
                        String g3=mf.item1.get(k).toString();
                        
                        System.out.println(g1+g2+g3);
                        //at1.add(g1+g2+g3);
                        at1.add(g1+"#"+g2+"#"+g3);
                    }
                }
            }
            System.out.println("at1 "+at1);
            String tt1="3- subsets\n\n";
            ArrayList at2=new ArrayList();
            ArrayList at3=new ArrayList();
            for(int i=0;i<at1.size();i++)
            {
                String s1=at1.get(i).toString();
                //char g1[]=s1.toCharArray();
                String g1[]=s1.split("#");
                int k=0;
                for(int j=1;j<mf.data.length;j++)
                {
                    String g2=mf.data[j][1];
                    if(g2.contains(String.valueOf(g1[0])) && g2.contains(String.valueOf(g1[1])) && g2.contains(String.valueOf(g1[2])))
                    k++;
                }
                if(k>0)
                {
                    at2.add(k);
                    at3.add(s1);
                    System.out.println(s1+" : "+k);
                    tt1=tt1+s1+" : "+k+"\n";
                }
               
                //txt=txt+s1+" : "+k+"\n";
            }
            */
            
            System.out.println("----> "+mf.item1);
            ArrayList at1=new ArrayList();
            String res="";
            for(int i=0;i<mf.item1.size();i++)
            {
                String g1=mf.item1.get(i).toString();
                for(int j=i+1;j<mf.item1.size();j++)
                {
                    String g2=mf.item1.get(j).toString();
                    for(int k=j+1;k<mf.item1.size();k++)
                    //for(int k=j+1;k<mf.item1.size();k+=2)
                    {
                        String g3=mf.item1.get(k).toString();
                        
                        System.out.println(g1+g2+g3);
                        //at1.add(g1+g2+g3);
                        at1.add(g1+"#"+g2+"#"+g3);
                        res=res+g1+"#"+g2+"#"+g3+" --> "+"Prefix Item : "+g1+"#"+g2+" --> Stem Item : "+g3+"\n\n";
                    }
                }
            }
            
            ArrayList at2=new ArrayList();
            
            for(int i=0;i<at1.size();i++)
            {
                String g1[]=at1.get(i).toString().split("#");
                String sg1=g1[0]+"#"+g1[1];
                for(int j=0;j<at1.size();j++)
                {
                    String g2[]=at1.get(j).toString().split("#");
                    String sg2=g2[0]+"#"+g2[1];
                    if(sg1.equals(sg2))
                    {
                        if(!(at2.contains(sg1)))
                            at2.add(sg1);
                    }
                    
                }                
                
            }
            
            
            
            System.out.println("at2 "+at2);
            
            String r1="";
            for(int i=0;i<at2.size();i++)
            {
                r1=r1+"Group "+(i+1)+" - Item Set\n";
                String g1=at2.get(i).toString();
                r1=r1+g1+"\n";
                int k1=0;
                for(int j=0;j<at1.size();j++)
                {
                    String g2=at1.get(j).toString();
                    if(g2.startsWith(g1))
                    {
                        String g3[]=g2.split("#");
                        r1=r1+"\t"+g3[2]+"\n";
                        
                        ArrayList list1=mf.itemSetCount[2];
                        for(int m=0;m<list1.size();m++)
                        {
                            String g4=list1.get(m).toString();
                            if(g4.startsWith(g2))
                            {
                                String d1[]=g4.split("#");
                                k1=k1+Integer.parseInt(d1[d1.length-1]);
                            }
                        }
                        
                    }
                }
                r1=r1+"Group Count : "+k1+"\n";
                r1=r1+"\n\n";
            }
            
            System.out.println("skip "+at1);
            SkipFrame sf=new SkipFrame(mf,at1);
            sf.setVisible(true);
            sf.setResizable(false);
            sf.setTitle("Skip and Complete");
            sf.jTextArea1.setText(res);
            sf.jTextArea2.setText(r1);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubsetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubsetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubsetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubsetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new BaseInfoFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
