/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dbca;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author ETPL_CH_01
 */
public class window extends javax.swing.JFrame {
Statement st,st1,st2;
     Connection con;
     ArrayList al=new ArrayList();
     ArrayList al1=new ArrayList();
     static String value1,value2;
     
    /**
     * Creates new form window
     */
    public window() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbca", "root", "");
            st = con.createStatement();
            st1 = con.createStatement();
            st2=con.createStatement();
            st.executeUpdate("truncate table words ");
//            st.executeUpdate("truncate table batch1");
//            st.executeUpdate("truncate table batch2");
            st.executeUpdate("truncate table batchfinal");
        } catch (ClassNotFoundException | SQLException e) {
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Batch Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Calculate Mean");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addGap(45, 45, 45)
                .addComponent(jButton2)
                .addGap(43, 43, 43)
                .addComponent(jButton3)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel1.setText("Sliding Window");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   try
   {
       int start=1;
      int windowmaxsize=10;
      for(int i=1;i<2;i++)
      {
          int j=1;
//          String query="select * from home where  tid between "+ start + " \t and \t " + (j*windowmaxsize);
//          System.out.println(query);
            ResultSet rs=st.executeQuery(" select * from home where  tid between "+ start + " \t and \t " + (j*windowmaxsize) );
            jTextArea1.append(" Batch 0 enters in window1 \n");
            while(rs.next())
            {
                String s1=rs.getString(2);
                jTextArea1.append(s1 + "\n");
                st1.executeUpdate("insert into batchfinal values('" +s1 +"')");
                al.add(s1);
            }
           
      }
      for(int i=1;i<2 ;i++)
      {
          int j=2;
          start=start+windowmaxsize;
            ResultSet rs=st.executeQuery(" select * from home where  tid between "+ start + " \t and \t " + (j*windowmaxsize) );
            jTextArea2.append(" Batch 1 enters in window2 + \n");
            while(rs.next())
            {
                String s1=rs.getString(2);
                jTextArea2.append(s1 + "\n");
                st1.executeUpdate("insert into batchfinal values('" +s1 +"')");
                al1.add(s1);
            }
      }
    JOptionPane.showMessageDialog(null," Batch 0 and Batch 1 entered into windows");
    jTextArea1.append(" \n \n -------------------------------------------------------- \n");
    jTextArea2.append(" \n \n --------------------------------------------------------\n");
   }
   catch(SQLException | HeadlessException e)
   {
       System.out.println(e.getMessage());
   }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     try
     {
         int count=0;
         int count1=0;
         int count2=0;
         int count3=0;
         int count4=0;
         int count5=0;
         for(int i=0;i<al.size();i++)
         {
//             System.out.println(al.get(i).toString());
             String var=(String) al.get(i);
             StringTokenizer str=new StringTokenizer(var, " #");
             while(str.hasMoreTokens())
             {
                 String bd=str.nextToken();
//                 st.executeUpdate("insert into words  values ('"+bd+ "','"+count +"')");
                 System.out.println(bd);
                 switch (bd) {
                     case "shapner":
                         count++;
                         st.executeUpdate("insert into words  values ('"+bd+ "','"+count +"','"+" "+"')");
                         break;
                     case "pen":
                         count1++;
                         st.executeUpdate("insert into words  values ('"+bd+ "','"+count1 +"','"+" "+"')");
                         break;
                     case "eraser":
                         count2++;
                         st.executeUpdate("insert into words  values ('"+bd+ "','"+count2+"','"+" "+"')");
                         break;
                     case "scale":
                         count3++;
                         st.executeUpdate("insert into words  values ('"+bd+ "','"+count3 +"','"+" "+"')");
                         break;
                     case "ink":
                         count4++;
                         st.executeUpdate("insert into words  values ('"+bd+ "','"+count4 +"','"+" "+"')");
                         break;
                     default:
                         count5++;
                         break;
                 }
             }
                   
         }
//         ResultSet rs=st.executeQuery("SELECT DISTINCT word FROM words");
//         while(rs.next())
//         {
//             String af=rs.getString(1);
//             ResultSet rs1=st1.executeQuery("select max(count) from words where word='"+af+ "'" );
              ResultSet rs1=st1.executeQuery("select count(distinct word) from words " );
                  while(rs1.next())
                  {
                 value1=rs1.getString(1);
                      jTextArea1.append("\n Batch 1 contains" + value1 + "\n");
//                      jTextArea1.append("count of "  + af + "is"  +  value + "\n" );
//                      st2.executeUpdate(" insert into  batch1 values ('"+af + "','" + value + "')");
                  }
//         }
          for(int i=0;i<al1.size();i++)
         {
//             System.out.println(al.get(i).toString());
             String var=(String) al1.get(i);
             StringTokenizer str=new StringTokenizer(var, " #");
             while(str.hasMoreTokens())
             {
                 String bd=str.nextToken();
//                 st.executeUpdate("insert into words  values ('"+bd+ "','"+count +"')");
                 System.out.println(bd);
                 switch (bd) {
                     case "shapner":
                         count++;
                         st.executeUpdate("insert into words2  values ('"+bd+ "','"+count +"')");
                         break;
                     case "pen":
                         count1++;
                         st.executeUpdate("insert into words2  values ('"+bd+ "','"+count1 +"')");
                         break;
                     case "eraser":
                         count2++;
                         st.executeUpdate("insert into words2  values ('"+bd+ "','"+count2+"')");
                         break;
                     case "scale":
                         count3++;
                         st.executeUpdate("insert into words2  values ('"+bd+ "','"+count3 +"')");
                         break;
                     case "ink":
                         count4++;
                         st.executeUpdate("insert into words2  values ('"+bd+ "','"+count4 +"')");
                         break;
                     default:
                         count5++;
                         break;
                 }
             }
                   
         }
//         ResultSet rs2=st.executeQuery("SELECT DISTINCT word FROM words2");
//         while(rs2.next())
//         {
//             String af=rs2.getString(1);
//             ResultSet rs1=st1.executeQuery("select max(count) from words2 where word='"+af+ "'" );
             ResultSet rs2=st1.executeQuery("select count(distinct word) from words " );
                  while(rs2.next())
                  {
                      
                     value2=rs2.getString(1);
                      jTextArea2.append("\n Batch 2 contains "  +  value2 + "\n" );
//                      st2.executeUpdate("insert into batch2 values('"+af+ "','" + value +"')" );
                  }
//         }
         
       JOptionPane.showMessageDialog(null,"values computed ");
     }
     catch(SQLException | HeadlessException e)
     {
         System.out.println(e.getMessage());
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      new computation().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new window().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
